run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - gofumpt
    - ineffassign
    - gosimple
    - unused
    - errcheck
    - gocritic
issues:
  exclude-use-default: false
