services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: servicesdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --log-bin-trust-function-creators=1 --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "app", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    environment:
      PORT: 8080
      LOG_LEVEL: info
      # database/sql DSN for go-sql-driver/mysql
      MYSQL_DSN: app:app@tcp(mysql:3306)/servicesdb?parseTime=true&charset=utf8mb4&collation=utf8mb4_0900_ai_ci
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  migrate:
    image: golang:1.22
    working_dir: /migrations
    volumes:
      - ./migrations:/migrations
    command: >
      sh -c "
        go install github.com/pressly/goose/v3/cmd/goose@v3.24.0 &&
        goose -dir /migrations mysql 'app:app@tcp(mysql:3306)/servicesdb?parseTime=true&multiStatements=true' up
      "
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
