services:
  mysql-test:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: servicesdb_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --log-bin-trust-function-creators=1 --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "app", "-papp"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data:
